version: '2'
services:
  mongomono-app:
    image: mongomono
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongomono-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=mongomono
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mongomono-mongodb:
    extends:
      file: mongodb.yml
      service: mongomono-mongodb
